using HotelManagement.Application.Features.Amenities;
using HotelManagement.Application.Features.Attendance;
using HotelManagement.Application.Features.AuditLogs;
using HotelManagement.Application.Features.Authentication.Services;
using HotelManagement.Application.Features.Availability;
using HotelManagement.Application.Features.Branches;
using HotelManagement.Application.Features.Buildings;
using HotelManagement.Application.Features.CheckIns;
using HotelManagement.Application.Features.CheckOuts;
using HotelManagement.Application.Features.Complaints;
using HotelManagement.Application.Features.Dashboard.Services;
using HotelManagement.Application.Features.Departments;
using HotelManagement.Application.Features.Deposits;
using HotelManagement.Application.Features.Discounts;
using HotelManagement.Application.Features.Employees;
using HotelManagement.Application.Features.FeatureFlags;
using HotelManagement.Application.Features.Floors;
using HotelManagement.Application.Features.Folios;
using HotelManagement.Application.Features.GoodsReceipts;
using HotelManagement.Application.Features.GuestDocuments;
using HotelManagement.Application.Features.GuestRequests;
using HotelManagement.Application.Features.GuestServices;
using HotelManagement.Application.Features.Guests.Services;
using HotelManagement.Application.Features.Hotels;
using HotelManagement.Application.Features.Housekeeping.Services;
using HotelManagement.Application.Features.Inventory;
using HotelManagement.Application.Features.Invoices.Services;
using HotelManagement.Application.Features.Laundry;
using HotelManagement.Application.Features.LeaveRequests;
using HotelManagement.Application.Features.LostAndFound;
using HotelManagement.Application.Features.Maintenance.Services;
using HotelManagement.Application.Features.MasterData.Services;
using HotelManagement.Application.Features.MeterReadings;
using HotelManagement.Application.Features.Notifications;
using HotelManagement.Application.Features.Payments;
using HotelManagement.Application.Features.Permissions;
using HotelManagement.Application.Features.Positions;
using HotelManagement.Application.Features.Profile.Services;
using HotelManagement.Application.Features.PurchaseOrders;
using HotelManagement.Application.Features.PurchaseRequests;
using HotelManagement.Application.Features.Rates;
using HotelManagement.Application.Features.Refunds;
using HotelManagement.Application.Features.Reports;
using HotelManagement.Application.Features.Reservations.Services;
using HotelManagement.Application.Features.Restaurant;
using HotelManagement.Application.Features.Roles;
using HotelManagement.Application.Features.RoomAssignments;
using HotelManagement.Application.Features.RoomChanges;
using HotelManagement.Application.Features.RoomInspections;
using HotelManagement.Application.Features.RoomTypes;
using HotelManagement.Application.Features.Rooms.Services;
using HotelManagement.Application.Features.SecurityIncidents;
using HotelManagement.Application.Features.Settings;
using HotelManagement.Application.Features.Shifts;
using HotelManagement.Application.Features.StayExtensions;
using HotelManagement.Application.Features.StockTransactions;
using HotelManagement.Application.Features.Suppliers;
using HotelManagement.Application.Features.Taxes;
using HotelManagement.Application.Features.Transportation;
using HotelManagement.Application.Features.Users.Services;
using HotelManagement.Application.Features.Utilities.Services;
using HotelManagement.Application.Features.UtilityMeters;
using HotelManagement.Application.Features.UtilityRates;
using HotelManagement.Application.Features.Warehouses;
using HotelManagement.Application.Common.Services;
using HotelManagement.Application.Mapping;

namespace HotelManagement.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services, IConfiguration configuration)
    {
        services.AddAutoMapper(cfg =>
        {
            var key = configuration["AutoMapper:LicenseKey"];
            if (!string.IsNullOrWhiteSpace(key)) cfg.LicenseKey = key;
        }, typeof(MappingProfile).Assembly);
        services.AddScoped(typeof(CatalogCrudService<>));
        services.AddScoped(typeof(OperationalCrudService<>));
        services.AddScoped<AmenitiesService>();
        services.AddScoped<AttendanceService>();
        services.AddScoped<AuditLogService>();
        services.AddScoped<AuthService>();
        services.AddScoped<AvailabilityService>();
        services.AddScoped<BranchesService>();
        services.AddScoped<BuildingsService>();
        services.AddScoped<CheckInService>();
        services.AddScoped<CheckOutService>();
        services.AddScoped<ComplaintsService>();
        services.AddScoped<DashboardService>();
        services.AddScoped<DepartmentsService>();
        services.AddScoped<DepositsService>();
        services.AddScoped<DiscountsService>();
        services.AddScoped<EmployeeService>();
        services.AddScoped<FeatureFlagsService>();
        services.AddScoped<FloorsService>();
        services.AddScoped<FolioService>();
        services.AddScoped<GoodsReceiptsService>();
        services.AddScoped<GuestDocumentsService>();
        services.AddScoped<GuestRequestsService>();
        services.AddScoped<GuestServicesService>();
        services.AddScoped<GuestService>();
        services.AddScoped<HotelsService>();
        services.AddScoped<HousekeepingService>();
        services.AddScoped<InventoryService>();
        services.AddScoped<InvoiceService>();
        services.AddScoped<LaundryService>();
        services.AddScoped<LeaveRequestsService>();
        services.AddScoped<LostAndFoundService>();
        services.AddScoped<MaintenanceService>();
        services.AddScoped<MasterDataService>();
        services.AddScoped<MeterReadingsService>();
        services.AddScoped<NotificationsService>();
        services.AddScoped<PaymentService>();
        services.AddScoped<PermissionsService>();
        services.AddScoped<PositionsService>();
        services.AddScoped<ProfileService>();
        services.AddScoped<PurchaseOrdersService>();
        services.AddScoped<PurchaseRequestsService>();
        services.AddScoped<RatesService>();
        services.AddScoped<RefundsService>();
        services.AddScoped<ReportsService>();
        services.AddScoped<ReservationService>();
        services.AddScoped<RestaurantService>();
        services.AddScoped<RolesService>();
        services.AddScoped<RoomAssignmentsService>();
        services.AddScoped<RoomChangesService>();
        services.AddScoped<RoomInspectionsService>();
        services.AddScoped<RoomTypesService>();
        services.AddScoped<RoomService>();
        services.AddScoped<SecurityIncidentsService>();
        services.AddScoped<SettingsService>();
        services.AddScoped<ShiftsService>();
        services.AddScoped<StayExtensionsService>();
        services.AddScoped<StockTransactionsService>();
        services.AddScoped<SuppliersService>();
        services.AddScoped<TaxesService>();
        services.AddScoped<TransportationService>();
        services.AddScoped<UserAdminService>();
        services.AddScoped<UtilityService>();
        services.AddScoped<UtilityMetersService>();
        services.AddScoped<UtilityRatesService>();
        services.AddScoped<WarehousesService>();
        return services;
    }
}